import type { NextPage } from 'next'
import Head from 'next/head'
import axios from 'axios'
import { useEffect } from 'react'
import { Button } from 'antd'

const Home: NextPage = () => {
  useEffect(()=>{
    axios({
      url: '/api/proxy/web/version/init',
      method: 'GET',
    }).then(res=>{
      console.log(res);
    })
  },[])
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <Button type="primary">Button</Button>
      </div>
    </div>
  )
}

export default Home
